prism.registerRegistry("components", prism.Component)
prism.registerRegistry("relations", prism.Relation)
prism.registerRegistry("targets", prism.Target, true)
prism.registerRegistry("cells", prism.Cell, true)
prism.registerRegistry("actions", prism.Action)
prism.registerRegistry("actors", prism.Actor, true)
prism.registerRegistry("messages", prism.Message)
prism.registerRegistry("decisions", prism.Decision)
prism.registerRegistry("systems", prism.System)
prism.registerRegistry("schedulers", prism.Scheduler)
